
const STORAGE_KEY="earlyEagleCompanionV2",DESIGN_W=1536,DESIGN_H=1024;
const defaults={pin:"",students:[],starIndex:0,starDate:"",aboutStar:"Each day, we celebrate one special friend who shines bright in our classroom!",schedule:["Community Meeting","Read Aloud","Centers","Small Groups","Lunch","Recess","Rest Time","Clean Up","Closing Circle"],scheduleDone:[],soundEnabled:true};
let state=load(),unlocked=false;const qs=s=>document.querySelector(s),qsa=s=>[...document.querySelectorAll(s)];
function load(){try{return Object.assign(JSON.parse(JSON.stringify(defaults)),JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}"))}catch{return JSON.parse(JSON.stringify(defaults))}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function fit(){const scale=Math.min(innerWidth/DESIGN_W,innerHeight/DESIGN_H);qs("#stage").style.transform=`scale(${scale})`}
addEventListener("resize",fit,{passive:true});addEventListener("orientationchange",()=>setTimeout(fit,80));
function dateKey(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function updateStar(){if(!state.students.length)return;const today=dateKey(),day=new Date().getDay();if(state.starDate!==today&&day>0&&day<6){if(state.starDate)state.starIndex=(state.starIndex+1)%state.students.length;state.starDate=today;save()}}
function currentStar(){return state.students.length?state.students[state.starIndex%state.students.length]:"Add class list"}
function render(){qs("#morning-date").textContent=new Date().toLocaleDateString(undefined,{weekday:"short",month:"short",day:"numeric"});updateStar();const n=currentStar();qs("#morning-star-name").textContent=n;qs("#star-name").textContent=n==="Add class list"?"Friend":n;qs("#about-star").textContent=state.aboutStar;qs("#friends-total").textContent=state.students.length;renderSchedule();renderNext()}
function renderSchedule(){const box=qs("#schedule-list");box.innerHTML="";state.schedule.forEach((x,i)=>{const b=document.createElement("button");b.type="button";b.className="schedule-item"+(state.scheduleDone.includes(i)?" done":"");b.innerHTML=`<span class="bubble">${state.scheduleDone.includes(i)?"✓":""}</span><span>${x}</span>`;b.addEventListener("click",()=>{state.scheduleDone=state.scheduleDone.includes(i)?state.scheduleDone.filter(n=>n!==i):[...state.scheduleDone,i];save();renderSchedule();renderNext()});box.appendChild(b)})}
function renderNext(){qs("#whats-next").textContent=state.schedule.find((_,i)=>!state.scheduleDone.includes(i))||"Wonderful day!"}
function scene(name){qsa(".scene").forEach(s=>s.classList.remove("active"));qs("#scene-"+name).classList.add("active")}
function toast(t){const e=qs("#toast");e.textContent=t;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),1700)}
function openTeacher(){qs("#teacher-modal").classList.add("open");qs("#pin-input").value="";qs("#pin-message").textContent="";qs("#pin-help").textContent=state.pin?"Enter your Teacher PIN.":"Create your Teacher PIN.";qs("#pin-panel").hidden=unlocked;qs("#settings-panel").hidden=!unlocked;if(unlocked)loadFields()}
function unlock(){const v=qs("#pin-input").value.trim();if(!state.pin){if(v.length<4){qs("#pin-message").textContent="Use at least 4 digits.";return}state.pin=v;save();unlocked=true}else if(v===state.pin)unlocked=true;else{qs("#pin-message").textContent="That PIN doesn't match.";return}qs("#pin-panel").hidden=true;qs("#settings-panel").hidden=false;loadFields()}
function loadFields(){qs("#students-input").value=state.students.join("\n");qs("#schedule-input").value=state.schedule.join("\n");qs("#about-input").value=state.aboutStar;qs("#sound-enabled").checked=state.soundEnabled;qs("#new-pin").value="";const s=qs("#star-index-input");s.innerHTML="";(state.students.length?state.students:["Add students first"]).forEach((n,i)=>{const o=document.createElement("option");o.value=i;o.textContent=n;o.selected=i===state.starIndex;s.appendChild(o)})}
function saveFields(){state.students=[...new Set(qs("#students-input").value.split(/\r?\n/).map(s=>s.trim()).filter(Boolean))];const sc=qs("#schedule-input").value.split(/\r?\n/).map(s=>s.trim()).filter(Boolean);state.schedule=sc.length?sc:defaults.schedule.slice();state.aboutStar=qs("#about-input").value.trim()||defaults.aboutStar;state.soundEnabled=qs("#sound-enabled").checked;const p=qs("#new-pin").value.trim();if(p)state.pin=p;state.starIndex=state.students.length?Math.min(Number(qs("#star-index-input").value||0),state.students.length-1):0;save();render();toast("Saved")}
document.addEventListener("click",e=>{const b=e.target.closest("[data-action]");if(!b)return;({"go-home":()=>scene("home"),"go-morning":()=>scene("morning"),"go-star":()=>scene("star"),"teacher-mode":openTeacher,"placeholder-friend":()=>toast("Choose a Friend is next"),"placeholder-centers":()=>toast("Center Choice is next"),"placeholder-timer":()=>toast("Timer is next"),"placeholder-cleanup":()=>toast("Clean Up is next"),"placeholder-lessons":()=>toast("Daily Lessons is next")}[b.dataset.action]||(()=>{}))()})
qs("#close-teacher").onclick=()=>qs("#teacher-modal").classList.remove("open");qs("#unlock-teacher").onclick=unlock;qs("#save-settings").onclick=saveFields;qs("#advance-star").onclick=()=>{if(state.students.length){state.starIndex=(state.starIndex+1)%state.students.length;state.starDate=dateKey();save();render();loadFields()}};qs("#reset-day").onclick=()=>{state.scheduleDone=[];save();render();toast("Day reset")};qs("#pin-input").addEventListener("keydown",e=>{if(e.key==="Enter")unlock()});
fit();render();
