(function(){
'use strict';
const STUDENT_KEY='eea-students-v1',ATTENDANCE_KEY='eea-attendance-present',CALENDAR_KEY='eea-school-calendar',STAR_KEY='eea-current-star',STATE_KEY='eea-star-state-v1';
const FALLBACK=['Avery','Bentley','Blakely','Brantley','Dylan','Easton','Emersyn','Everleigh','Grayson','Harper','Hudson','Jaxson','Kinsley','Liam','Maverick','Oakley','Sawyer','Warren','Wyatt','Zoey'];
function dateKey(d=new Date()){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function roster(){let a=[];try{const x=JSON.parse(localStorage.getItem(STUDENT_KEY)||'null');if(Array.isArray(x)&&x.length)a=x.filter(s=>s&&s.active!==false&&String(s.name||'').trim()).map((s,i)=>({id:String(s.id||('s'+i)),name:String(s.name).trim()}))}catch(e){}if(!a.length)a=FALLBACK.map((name,i)=>({id:'s'+(i+1),name}));a.sort((x,y)=>x.name.localeCompare(y.name));return a}
function presentIds(){const r=roster(),byId=new Map(r.map(s=>[s.id,s]));try{const x=JSON.parse(localStorage.getItem(ATTENDANCE_KEY)||'[]');if(!Array.isArray(x))return [];return [...new Set(x.map(v=>String(v)).filter(id=>byId.has(id)))]}catch(e){return []}}
function isSchoolDay(d=new Date()){try{const cal=JSON.parse(localStorage.getItem(CALENDAR_KEY)||'{}')||{},entry=cal[dateKey(d)];if(entry)return entry.type==='school'}catch(e){}const day=d.getDay();return day>=1&&day<=5}
function freshState(){const r=roster(),saved=localStorage.getItem(STAR_KEY)||'',idx=Math.max(0,r.findIndex(s=>s.name===saved));return {version:1,cycle:1,servedIds:saved&&idx>=0?[r[idx].id]:[],pendingIds:[],nextIndex:r.length?((idx+1)%r.length):0,lastResolvedDate:'',currentId:saved&&idx>=0?r[idx].id:'',currentName:saved&&idx>=0?r[idx].name:''}}
function load(){let s=null;try{s=JSON.parse(localStorage.getItem(STATE_KEY)||'null')}catch(e){}if(!s||typeof s!=='object')s=freshState();const r=roster(),valid=new Set(r.map(x=>x.id));s.servedIds=Array.isArray(s.servedIds)?s.servedIds.filter(id=>valid.has(id)):[];s.pendingIds=Array.isArray(s.pendingIds)?s.pendingIds.filter(id=>valid.has(id)&&!s.servedIds.includes(id)):[];s.nextIndex=Math.max(0,Math.min(r.length-1,Number(s.nextIndex)||0));if(s.currentId&&!valid.has(s.currentId)){s.currentId='';s.currentName=''}if(s.currentId){const c=r.find(x=>x.id===s.currentId);s.currentName=c?c.name:''}s.cycle=Number(s.cycle)||1;s.version=1;return s}
function save(s){localStorage.setItem(STATE_KEY,JSON.stringify(s));if(s.currentName)localStorage.setItem(STAR_KEY,s.currentName);return s}
function firstUnservedIndex(s,start){const r=roster();if(!r.length)return 0;for(let n=0;n<r.length;n++){const i=(start+n)%r.length;if(!s.servedIds.includes(r[i].id))return i}return 0}
function resetCycleIfNeeded(s){const r=roster();if(r.length&&s.servedIds.length>=r.length){s.cycle=(s.cycle||1)+1;s.servedIds=[];s.pendingIds=[];s.nextIndex=0}return s}
function resolveToday(){const d=new Date(),today=dateKey(d),r=roster(),present=presentIds();let s=load();if(!r.length||!isSchoolDay(d)||!present.length)return s;if(s.lastResolvedDate===today&&s.currentId)return s;resetCycleIfNeeded(s);
let chosen=null,chosenWasPending=false;
for(const id of s.pendingIds){if(present.includes(id)&&!s.servedIds.includes(id)){chosen=r.find(x=>x.id===id)||null;if(chosen){chosenWasPending=true;break}}}
if(!chosen){const firstMissing=[];for(let n=0;n<r.length;n++){const i=(s.nextIndex+n)%r.length,student=r[i];if(s.servedIds.includes(student.id))continue;if(present.includes(student.id)){chosen=student;break}if(!s.pendingIds.includes(student.id)){s.pendingIds.push(student.id);firstMissing.push(student.id)}}}
if(!chosen)return save(s);
if(!s.servedIds.includes(chosen.id))s.servedIds.push(chosen.id);s.pendingIds=s.pendingIds.filter(id=>id!==chosen.id);s.currentId=chosen.id;s.currentName=chosen.name;s.lastResolvedDate=today;
const chosenIndex=r.findIndex(x=>x.id===chosen.id);if(s.pendingIds.length){const pendingIndexes=s.pendingIds.map(id=>r.findIndex(x=>x.id===id)).filter(i=>i>=0);if(pendingIndexes.length)s.nextIndex=pendingIndexes[0]}else{s.nextIndex=firstUnservedIndex(s,(chosenIndex+1)%r.length)}
return save(s)}
function overrideById(id){const r=roster(),c=r.find(x=>x.id===id);if(!c)return load();let s=load();resetCycleIfNeeded(s);if(!s.servedIds.includes(id))s.servedIds.push(id);s.pendingIds=s.pendingIds.filter(x=>x!==id);s.currentId=id;s.currentName=c.name;s.lastResolvedDate=dateKey(new Date());const i=r.findIndex(x=>x.id===id);s.nextIndex=firstUnservedIndex(s,(i+1)%r.length);return save(s)}
function nextCandidate(){const r=roster(),s=load();for(const id of s.pendingIds){if(!s.servedIds.includes(id)){const c=r.find(x=>x.id===id);if(c)return c}}for(let n=0;n<r.length;n++){const i=(s.nextIndex+n)%r.length;if(!s.servedIds.includes(r[i].id))return r[i]}return r[0]||null}
function current(){const r=roster(),s=load(),c=r.find(x=>x.id===s.currentId);if(c)return c;const byName=r.find(x=>x.name===localStorage.getItem(STAR_KEY));return byName||r[0]||null}
function status(){return {state:load(),roster:roster(),presentIds:presentIds(),current:current(),next:nextCandidate(),schoolDay:isSchoolDay(new Date()),today:dateKey(new Date())}}
window.EEAStar={resolveToday,overrideById,current,nextCandidate,status,roster,isSchoolDay,dateKey,loadState:load};
})();