// Source/DOM regressions. Independent originals are pinned in _fixtures.cjs;
// native joint history, image pixels and viewport geometry belong to _browser.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {JSDOM,ResourceLoader,VirtualConsole}=require('jsdom');
const {implForWrapper}=require('jsdom/lib/jsdom/living/generated/utils');const {serializeURL}=require('whatwg-url');
const fixtures=require('./test_week12_readaloud_tuesday_fixtures.cjs');
const root=path.resolve(process.env.APP_ROOT||process.env.WEEK12_READALOUD_APP_ROOT||path.join(__dirname,'../v6-test'));
const read=f=>fs.readFileSync(path.join(root,f),'utf8'),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),copy=v=>JSON.parse(JSON.stringify(v)),words=s=>s.replace(/\s+/g,' ').trim();
const plan=JSON.parse(read('week12-read-aloud-tuesday-plan.json')),steps=plan.steps,last=steps.length-1,origin='https://eea.test/v6-test/',assetRoot='assets/focus-3s/unit-2/week-4/festival-of-colors/';
const delay=ms=>new Promise(r=>setTimeout(r,ms));async function until(check,label){for(let i=0;i<300;i++){if(check())return;await delay(10);}assert.fail(label);}
class Files extends ResourceLoader{fetch(url){if(!url.startsWith(origin))return null;return Promise.resolve(fs.readFileSync(path.join(root,decodeURIComponent(new URL(url).pathname.slice('/v6-test/'.length)))));}}
function open(embedded=false,query='week=12&day=Tuesday&section=0'){
 const errors=[],navigations=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const file=embedded?'lesson-runner-week12.html':'week12-read-aloud.html';
 const w=new JSDOM(read(file),{url:origin+file+'?'+query,runScripts:'dangerously',resources:new Files(),virtualConsole:vc,beforeParse(w){implForWrapper(w.location)._locationObjectNavigate=url=>navigations.push(serializeURL(url));const Native=w.Date;w.Date=class extends Native{constructor(...a){super(...(a.length?a:['2026-10-05T12:00:00Z']));}static now(){return new Native('2026-10-05T12:00:00Z').getTime();}};}}).window;return{w,errors,navigations,embedded};
}
async function ready(a){await until(()=>a.w.document.readyState==='complete','Document ready');const w=a.embedded?a.w.document.getElementById('frame').contentWindow:a.w;await until(()=>w.document.readyState==='complete'&&typeof w.EEASectionState==='function','Reader initialized');return w;}
function close(a){assert.deepEqual(a.errors,[]);a.w.close();}
function expected(step,stop=0){return{step,index:step,total:steps.length,atStart:step===0,atEnd:step===last&&stop===steps[step].stops.length,stopPending:stop<steps[step].stops.length,vocabulary:!!steps[step].vocabulary,stop};}
function check(a,w,step,stop=0){assert.deepEqual(copy(w.EEASectionState()),expected(step,stop));const s=steps[step],d=w.document;assert.equal(d.getElementById('bookImg').getAttribute('src'),s.img);assert.equal(d.getElementById('teachingStop').hidden,stop===0);assert.equal(d.getElementById('stopText').textContent,stop?s.stops[stop-1]:'');assert.equal(d.getElementById('prompt').textContent,s.prompt);assert.equal(d.querySelector('.stage').classList.contains('spread'),!!s.bookPage);assert.equal(d.getElementById('teacherNotes').open,false);assert(d.getElementById('teacherText').textContent.includes(s.note));for(const [win,day]of [[a.w,a.embedded?'1':'Tuesday'],[w,'Tuesday']]){const p=new URL(win.location.href).searchParams;assert.equal(p.get('week'),'12');assert.equal(p.get('day'),day);assert.equal(p.get('section'),'0');assert.equal(p.get('step'),String(step));assert.equal(p.get('stop'),String(stop));for(const field of ['book','center','review'])assert(!p.has(field));}assert.deepEqual(a.navigations,[],'No unexpected redirect');}
function exit(a,day=1){assert.equal(a.navigations.length,1,'Exactly one top-level navigation');const u=new URL(a.navigations[0]);assert.equal(u.pathname,'/v6-test/daily-lessons.html');assert.equal(u.searchParams.get('week'),'12');assert.equal(u.searchParams.get('day'),String(day));assert.equal(a.w.localStorage.getItem('eea-lesson-auto-resume'),null);}
function imageSize(bytes){if(bytes.readUInt32BE(0)===0x89504e47)return[bytes.readUInt32BE(16),bytes.readUInt32BE(20)];assert.equal(bytes.readUInt16BE(0),0xffd8);let i=2;while(i<bytes.length){assert.equal(bytes[i++],0xff);while(bytes[i]===0xff)i++;const m=bytes[i++],len=bytes.readUInt16BE(i);if([0xc0,0xc1,0xc2].includes(m))return[bytes.readUInt16BE(i+5),bytes.readUInt16BE(i+3)];i+=len;}assert.fail('Image header');}
function integrity(){
 assert.equal(plan.title,'Festival of Colors');assert.equal(plan.authors,'Kabir Sehgal and Surishtha Sehgal');assert.equal(plan.illustrator,'Vashti Harrison');assert.match(plan.read,/Read 2/);assert.match(plan.read,/Retell|sequenc|summar/i);assert.equal(steps.length,26);assert.equal(new Set(steps.map(s=>s.id)).size,26);
 const manifest=JSON.parse(read(assetRoot+'source-manifest.json'));assert.equal(manifest.source,fixtures.sourceGuide);assert.deepEqual(manifest.readingOrder,fixtures.order);assert.equal(manifest.images.length,21);
 for(const original of fixtures.images){const file=original.file||'guide-'+String(original.sourceSlide).padStart(2,'0')+'.jpg',bytes=fs.readFileSync(path.join(root,assetRoot,file)),actual=manifest.images.find(x=>x.file===file);assert(actual);assert.equal(hash(bytes),original.sha256,'Original bytes '+file);assert.deepEqual(imageSize(bytes),[original.width,original.height]);for(const key of ['sha256','width','height'])assert.equal(actual[key],original[key]);}
 const book=steps.filter(s=>s.kind==='book');assert.deepEqual(book.map(s=>s.sourceSlide),fixtures.order);assert.deepEqual(book.flatMap(s=>s.printedPages),Array.from({length:30},(_,i)=>i+1),'Cover/title then all printed pages 1–30 exactly once');
 for(const s of book){assert.equal(s.bookPage,true);assert.equal(s.img,assetRoot+'guide-'+String(s.sourceSlide).padStart(2,'0')+'.jpg');if(s.sourceSlide>=3)assert(words(s.note).includes(words(fixtures.guideNotes[s.sourceSlide])),'Every guide commentary word retained: '+s.sourceSlide);}
 const stopSteps=steps.filter(s=>s.stops.length);assert.deepEqual(stopSteps.map(s=>s.sourceSlide),[4,8,10,11,13],'Independently verified Read2 page mapping');assert.equal(stopSteps.flatMap(s=>s.stops).length,5);assert.deepEqual(stopSteps.map(s=>s.sourcePageLabel),['page 4','pages 5-12','pages 13-14','page 15','pages 11-13']);assert.deepEqual(stopSteps[4].verifiedResponsePages,[17,18,19,20,21,22]);assert.deepEqual(stopSteps[4].verifiedResponseSlides,[9,12,13]);
 const sourceStops=[
  'Chintoo and Mintoo are getting ready for Holi. What do they do first to prepare?',
  'Yes, they gather flowers. They gather red hibiscus, purple orchids, orange marigolds, and blue irises. After they gather the flowers, what do they do?',
  'They separate, or sort, the flowers, so they have piles of flowers and piles of stems and leaves, and then they press the flowers into powders.',
  'Chintoo and Mintoo are ready to celebrate Holi. Who do they gather with?',
  'Yes, they gather with their parents, their friends, and their neighbors, their community.'
 ];
 stopSteps.forEach((s,i)=>assert(words(s.stops[0]).includes(sourceStops[i]),'Full source Read2 stop '+i));
 const vocab=steps.filter(s=>s.vocabulary);assert.deepEqual(vocab.map(s=>s.word),['bloom','festival','separate','neighbor','forgive']);assert.deepEqual(vocab.map(s=>s.prompt),['when a flower opens','a celebration','to sort','someone who lives near you','to stop being upset or angry at someone']);assert.deepEqual(vocab.map(s=>s.sourceSlide),[3,3,10,13,16]);for(const s of vocab){const start=steps.findIndex(p=>p.id===s.sourceStep),end=steps.indexOf(s);assert(start>=0&&start<end);assert(steps.slice(start+1,end).every(p=>p.vocabulary&&p.sourceStep===s.sourceStep),'Vocabulary follows its original spread');}
 const source=words(plan.sourceNotes.flatMap(s=>s.paragraphs).join(' '));for(const [name,text]of [['common guidance',fixtures.commonGuidance],['Read2 lesson',fixtures.lessonRead2],['full differentiated original',fixtures.differentiatedOriginal]])assert(source.includes(words(text)),'Every original '+name+' word retained independently');
 assert.match(plan.teacherNotes,/physical book|back matter/);assert.match(plan.teacherNotes,/11[–-]13/);assert.match(plan.teacherNotes,/17[–-]22/);assert.match(steps.at(-1).note,/Finish returns to Tuesday/);
 const after=steps.filter(s=>s.kind==='after');assert.equal(after.length,2);const afterText=words(after.map(s=>s.prompt+' '+s.note).join(' '));for(const phrase of ['What is something you celebrate with your family, your friends, or your neighbors?','How do you celebrate? What do you do? How do you prepare? How does it feel when you celebrate?'])assert(afterText.includes(phrase),'Full Read2 personal celebration question');
 assert(words(steps[0].prompt).includes('Today we will read Festival of Colors again!'),'Read2 opening');assert(words(steps.at(-1).prompt).includes('Today we read Festival of Colors for the second time.'),'Read2 closing');
 assert.deepEqual([...read('week12-read-aloud.html').matchAll(/<script src="([^"]+)"/g)].map(m=>m[1]),['week12-read-aloud-plan-v1.js','week12-read-aloud-tuesday-plan-v2.js','week12-read-aloud-wednesday-plan-v1.js','week12-read-aloud-thursday-plan-v1.js','week12-read-aloud-v4.js']);const sw=read('sw.js');assert.match(sw,/const CACHE='eea-companion-v105'/);for(const file of ['week12-read-aloud.html','week12-read-aloud-v4.js','week12-read-aloud-plan-v1.js','week12-read-aloud-plan.json','week12-read-aloud-tuesday-plan-v2.js','week12-read-aloud-tuesday-plan.json','lesson-runner-week12.html','week12-read-aloud-wednesday-plan-v1.js','week12-read-aloud-thursday-plan-v1.js','week12-read-aloud-wednesday-plan.json'])assert(sw.includes("'./"+file+"'"),'Worker caches '+file);assert.equal(hash(read('week12-read-aloud-v1.js')),fixtures.oldReaderSha256,'Prior Monday runtime remains byte-for-byte available');assert.equal(hash(read('week11-read-aloud-v4.js')),require('./test_week12_readaloud_fixtures.cjs').oldReaderSha256,'Week3 stable runtime remains untouched');
}
(async()=>{
 integrity();
 for(const embedded of [false,true]){
  const a=open(embedded),w=await ready(a),d=w.document;assert.deepEqual(copy(w.EEAReadAloudPlan),plan);assert.equal(d.querySelectorAll('iframe').length,0);
  const sourceNotes=[];for(const node of d.getElementById('sourceNotes').children){if(node.tagName==='H3')sourceNotes.push({title:node.textContent,paragraphs:[]});else if(node.tagName==='P')sourceNotes.at(-1).paragraphs.push(node.textContent);}assert.deepEqual(sourceNotes,plan.sourceNotes);
  assert.deepEqual([...d.querySelectorAll('#teacherNotes a')].map(a=>[a.textContent,a.getAttribute('href')]),[['Open original lesson plan',plan.source],...plan.resources]);for(const link of d.querySelectorAll('#teacherNotes a')){assert.equal(link.target,'_blank');assert(link.rel.includes('noopener')&&link.rel.includes('noreferrer'));}
  const baseline=a.w.history.length;
  for(let i=0;i<steps.length;i++){
   check(a,w,i);const url=a.w.location.href,len=a.w.history.length,st=copy(w.EEASectionState());for(let n=0;n<3;n++){d.querySelector('#teacherNotes summary').click();d.querySelector('#teacherNotes summary').click();}assert.equal(a.w.location.href,url);assert.equal(a.w.history.length,len);assert.deepEqual(copy(w.EEASectionState()),st);
   if(steps[i].discussionImages){const buttons=d.querySelectorAll('#discussionControls button');assert.equal(buttons.length,2);for(let n=0;n<2;n++){buttons[n].click();assert.equal(d.getElementById('bookImg').getAttribute('src'),steps[i].discussionImages[n].img);assert.equal(buttons[n].getAttribute('aria-pressed'),'true');assert.deepEqual(copy(w.EEASectionState()),st);assert.equal(a.w.location.href,url);assert.equal(a.w.history.length,len);}buttons[steps[i].sourceSlide===16?0:1].click();}
   for(let stop=1;stop<=steps[i].stops.length;stop++){d.getElementById('next').click();check(a,w,i,stop);}if(i<last)d.getElementById('next').click();
  }
  assert.equal(a.w.history.length,baseline+last+5,'One semantic entry for each screen advance and source stop');assert.match(d.getElementById('next').textContent,/Finish Read Aloud/);a.w.localStorage.setItem('eea-lesson-auto-resume','enabled');for(let n=0;n<5;n++)d.getElementById('next').click();exit(a);close(a);
  for(const s of steps.filter(s=>s.stops.length||s.vocabulary)){const i=steps.indexOf(s),a=open(embedded,'week=12&day=Tuesday&section=0&step='+i+'&stop='+s.stops.length),w=await ready(a);check(a,w,i,s.stops.length);w.document.getElementById('prev').click();check(a,w,s.vocabulary?steps.findIndex(p=>p.id===s.sourceStep):i-1);a.w.history.back();await until(()=>w.EEASectionState().step===i,'Back restores stop/vocab');check(a,w,i,s.stops.length);close(a);}
  for(const [raw,rawStop,index,stop]of [['bad','bad',0,0],['-1','-1',0,0],['1.5','.5',0,0],['Infinity','NaN',0,0],['999','999',last,0],[String(steps.findIndex(s=>s.stops.length)),'999',steps.findIndex(s=>s.stops.length),1]]){const a=open(embedded,'week=12&day=Tuesday&section=0&step='+raw+'&stop='+rawStop+'&book=x&center=x&review=1'),w=await ready(a);check(a,w,index,stop);assert.equal(a.w.history.length,1);for(let n=0;n<4;n++){a.w.dispatchEvent(new a.w.Event('pageshow'));a.w.document.getElementById('frame')?.dispatchEvent(new a.w.Event('load'));}check(a,w,index,stop);close(a);}
  for(const [button,index]of [['prev',0],['backBtn',0],['backBtn',last],['next',last]]){const a=open(embedded,'week=12&day=Tuesday&section=0&step='+index),w=await ready(a);a.w.localStorage.setItem('eea-lesson-auto-resume','enabled');for(let n=0;n<5;n++)w.document.getElementById(button).click();exit(a);close(a);}
  for(const [day,target]of [['Friday',4],['4',4],['',0],['bad',0],['-1',0],['5',0],['1.5',0],['Monday%20',0]]){const a=open(embedded,'week=12&section=0'+(day?'&day='+day:''));await until(()=>a.navigations.length,'Invalid day guarded');exit(a,target);assert.equal(a.w.EEAReadAloudPlan,undefined);close(a);}
  for(const named of ['Tuesday','1']){const a=open(embedded,'week=12&day='+named+'&section=0'),w=await ready(a);check(a,w,0);close(a);}
  // Wednesday is now verified too; named and numeric day routes select Read3.
  for(const day of ['Wednesday','2']){const a=open(embedded,'week=12&day='+day+'&section=0'),w=await ready(a);assert.match(w.EEAReadAloudPlan.read,/Read 3/);assert.equal(w.EEASectionState().step,0);assert.equal(new URL(a.w.location.href).searchParams.get('day'),embedded?'2':'Wednesday');assert.deepEqual(a.navigations,[]);close(a);}
  for(const day of ['Thursday','3']){const a=open(embedded,'week=12&day='+day+'&section=0'),w=await ready(a);assert.equal(w.EEAReadAloudPlan.title,'Dog’s Colorful Day');assert.match(w.EEAReadAloudPlan.read,/Read 1/);assert.equal(w.EEASectionState().step,0);assert.equal(new URL(a.w.location.href).searchParams.get('day'),embedded?'3':'Thursday');assert.deepEqual(a.navigations,[]);close(a);}
  for(const section of ['1','2','-1','bad','0.5','']){const a=open(embedded,'week=12&day=Tuesday&section='+section);await until(()=>a.navigations.length,'Invalid section guarded');exit(a);close(a);}
 }
 console.log('PASS: Tuesday independent full Read2/differentiated source, 21 original assets, 26 screens, five mapped stops, five vocabulary screens, source DOM, history/normalization and same-Tuesday exits');
})().catch(e=>{console.error(e);process.exitCode=1;});
