// Source/DOM regressions. Independent originals are pinned in _fixtures.cjs;
// native joint history, image pixels and viewport geometry belong to _browser.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {JSDOM,ResourceLoader,VirtualConsole}=require('jsdom');
const {implForWrapper}=require('jsdom/lib/jsdom/living/generated/utils');const {serializeURL}=require('whatwg-url');
const fixtures=require('./test_week12_readaloud_thursday_fixtures.cjs');
const root=path.resolve(process.env.APP_ROOT||process.env.WEEK12_READALOUD_APP_ROOT||path.join(__dirname,'../v6-test'));
const read=f=>fs.readFileSync(path.join(root,f),'utf8'),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),copy=v=>JSON.parse(JSON.stringify(v)),words=s=>s.replace(/\s+/g,' ').trim();
const plan=JSON.parse(read('week12-read-aloud-thursday-plan.json')),steps=plan.steps,last=steps.length-1,origin='https://eea.test/v6-test/',assetRoot='assets/focus-3s/unit-2/week-4/dogs-colorful-day/';
const delay=ms=>new Promise(r=>setTimeout(r,ms));async function until(check,label){for(let i=0;i<300;i++){if(check())return;await delay(10);}assert.fail(label);}
class Files extends ResourceLoader{fetch(url){if(!url.startsWith(origin))return null;return Promise.resolve(fs.readFileSync(path.join(root,decodeURIComponent(new URL(url).pathname.slice('/v6-test/'.length)))));}}
function open(embedded=false,query='week=12&day=Thursday&section=0'){
 const errors=[],navigations=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const file=embedded?'lesson-runner-week12.html':'week12-read-aloud.html';
 const w=new JSDOM(read(file),{url:origin+file+'?'+query,runScripts:'dangerously',resources:new Files(),virtualConsole:vc,beforeParse(w){implForWrapper(w.location)._locationObjectNavigate=url=>navigations.push(serializeURL(url));const Native=w.Date;w.Date=class extends Native{constructor(...a){super(...(a.length?a:['2026-10-05T12:00:00Z']));}static now(){return new Native('2026-10-05T12:00:00Z').getTime();}};}}).window;return{w,errors,navigations,embedded};
}
async function ready(a){await until(()=>a.w.document.readyState==='complete','Document ready');const w=a.embedded?a.w.document.getElementById('frame').contentWindow:a.w;await until(()=>w.document.readyState==='complete'&&typeof w.EEASectionState==='function','Reader initialized');return w;}
function close(a){assert.deepEqual(a.errors,[]);a.w.close();}
function expected(step,stop=0){return{step,index:step,total:steps.length,atStart:step===0,atEnd:step===last&&stop===steps[step].stops.length,stopPending:stop<steps[step].stops.length,vocabulary:!!steps[step].vocabulary,stop};}
function check(a,w,step,stop=0){assert.deepEqual(copy(w.EEASectionState()),expected(step,stop));const s=steps[step],d=w.document;assert.equal(d.getElementById('bookImg').getAttribute('src'),s.img);assert.equal(d.getElementById('bookImg').hidden,!s.img);assert.equal(d.getElementById('icon').hidden,!!s.img);if(s.physicalBook)assert.match(d.getElementById('bookCue').textContent+' '+d.getElementById('bookNote').textContent,/physical|classroom book/i);assert.equal(d.getElementById('teachingStop').hidden,stop===0);assert.equal(d.getElementById('stopText').textContent,stop?s.stops[stop-1]:'');assert.equal(d.getElementById('prompt').textContent,s.prompt);assert.equal(d.querySelector('.stage').classList.contains('spread'),!!s.bookPage);assert.equal(d.getElementById('teacherNotes').open,false);assert(d.getElementById('teacherText').textContent.includes(s.note));for(const [win,day]of [[a.w,a.embedded?'3':'Thursday'],[w,'Thursday']]){const p=new URL(win.location.href).searchParams;assert.equal(p.get('week'),'12');assert.equal(p.get('day'),day);assert.equal(p.get('section'),'0');assert.equal(p.get('step'),String(step));assert.equal(p.get('stop'),String(stop));for(const field of ['book','center','review'])assert(!p.has(field));}assert.deepEqual(a.navigations,[],'No unexpected redirect');}
function exit(a,day=3){assert.equal(a.navigations.length,1,'Exactly one top-level navigation');const u=new URL(a.navigations[0]);assert.equal(u.pathname,'/v6-test/daily-lessons.html');assert.equal(u.searchParams.get('week'),'12');assert.equal(u.searchParams.get('day'),String(day));assert.equal(a.w.localStorage.getItem('eea-lesson-auto-resume'),null);}
function imageSize(bytes){if(bytes.readUInt32BE(0)===0x89504e47)return[bytes.readUInt32BE(16),bytes.readUInt32BE(20)];assert.equal(bytes.readUInt16BE(0),0xffd8);let i=2;while(i<bytes.length){assert.equal(bytes[i++],0xff);while(bytes[i]===0xff)i++;const m=bytes[i++],len=bytes.readUInt16BE(i);if([0xc0,0xc1,0xc2].includes(m))return[bytes.readUInt16BE(i+5),bytes.readUInt16BE(i+3)];i+=len;}assert.fail('Image header');}
function integrity(){
 assert.equal(fixtures.sourceCommit,'e41eaf6f59e4636a1682fa122a69fcd897cb144b');for(const key of ['oldWorker','oldReader','oldHtml','oldOverview','oldRunner','oldMondayPlan','oldMondayJson','oldTuesdayPlan','oldTuesdayJson','oldWednesdayPlan','oldWednesdayJson'])assert.equal(hash(fixtures[key]),fixtures[key+'Sha256'],'Exact immutable base Git snapshot '+key);
 assert.equal(plan.title,'Dog’s Colorful Day');assert.equal(plan.authors,'Emma Dodd');assert.equal(plan.illustrator,'Emma Dodd');assert.match(plan.read,/Read 1/);assert.match(plan.read,/Introduce/i);assert.equal(new Set(steps.map(s=>s.id)).size,steps.length);
 const manifest=JSON.parse(read(assetRoot+'source-manifest.json'));assert.deepEqual(manifest.sourceFiles,fixtures.sourceFiles,'Independent retrieved standard-source PDF hashes');
 assert.equal(manifest.publishedImageFiles.length,17);for(const original of fixtures.images){const bytes=fs.readFileSync(path.join(root,assetRoot,original.file)),entry=manifest.publishedImageFiles.find(i=>i.file===original.file);assert(entry);assert.equal(hash(bytes),original.sha256,'Exact original embedded book bytes '+original.file);assert.deepEqual(imageSize(bytes),[original.width,original.height]);for(const key of ['sha256','width','height','sourceClipping'])assert.equal(entry[key],original[key]);assert.equal(entry.sourcePdfPage,original.sourcePage);assert.deepEqual(entry.printedPages,original.bookPages||[]);}
 for(const file of fs.readdirSync(path.join(root,assetRoot))){if(/\.(?:png|jpe?g|webp|gif|svg)$/i.test(file))assert(fixtures.images.some(i=>i.file===file),'No stock photograph, arrow, symbol strip or replacement artwork: '+file);}
 const book=steps.filter(s=>s.kind==='book'||s.kind==='physical-book');assert.deepEqual(book.map(s=>path.basename(s.img)),fixtures.bookOrder,'All 17 original scans once in verified reading order');assert.deepEqual(book.map(s=>s.printedPages||[]),fixtures.bookPages);assert.deepEqual(book.flatMap(s=>s.printedPages),Array.from({length:29},(_,i)=>i+1),'Cover then book pages 1–29 exactly once');
 for(const step of steps){if(step.vocabulary){assert.equal(step.img,null);assert.equal(step.bookPage,false);}else{assert(fixtures.images.some(i=>assetRoot+i.file===step.img),'Every non-vocabulary visual is an exact original book scan');}}for(const step of book)assert.equal(step.bookPage,true,'Original reading pages use the large book view');
 const source=words(plan.sourceNotes.flatMap(s=>s.paragraphs).join(' '));for(const [name,text]of [['common guidance',fixtures.commonGuidance],['complete Read1 lesson',fixtures.lessonRead1]])assert(source.includes(words(text)),'Every original '+name+' word is preserved independently');
 assert.equal(hash(fixtures.lessonRead1),fixtures.lessonRead1Sha256,'Independent original lesson oracle');assert.match(plan.teacherNotes,/physical|classroom book/i);assert.match(plan.teacherNotes,/not.*publish|not.*host|restrict|permission|copyright|physical/i);assert.match(plan.imageProvenanceNote,/original|source/i);assert.match(plan.bookImageNote+' '+plan.physicalBookNote,/physical|classroom book/i);assert.match(plan.teacherNotes,/clip|cut off/i);
 const stopSteps=steps.filter(s=>s.stops.length);assert.equal(stopSteps.flatMap(s=>s.stops).length,fixtures.stopCount);assert.deepEqual(stopSteps.map(s=>s.printedPages),[[3,4],[7,8],[11,12],[13,14],[19,20],[21,22],[23],[24]],'Every gate is on its independent literal Read1 page');assert.equal(steps.length,33,'Complete approved book/vocabulary/teaching sequence');
 for(const original of fixtures.teachingStops){const matched=steps.filter(s=>(s.kind==='book'||s.kind==='physical-book')&&(s.printedPages||[]).some(p=>original.pages.includes(p)));assert(matched.length,'Verified source pages '+original.pages);for(const text of original.text)assert(words(matched.flatMap(s=>[...s.stops,s.note]).join(' ')).includes(words(text)),'Full original prompt at verified event '+text);}
 const predictions=steps.filter(s=>s.kind==='prediction');assert.equal(predictions.length,2,'Both original before-reading predictions get their own screen');for(const original of fixtures.predictions){const i=steps.findIndex(s=>s.kind==='prediction'&&JSON.stringify(s.printedPages)===JSON.stringify(original));assert(i>=0);assert(['book','physical-book'].includes(steps[i+1].kind));assert.deepEqual(steps[i+1].printedPages,original,'Prediction occurs before reading its physical-book spread');assert.equal(steps[i].img,steps[i+1].img,'Original prediction image matches following full-size spread');assert.equal(steps[i].prompt,'What do you think will happen? How do you know?');assert.match(steps[i].note,/before reading/i);}
 const vocab=steps.filter(s=>s.vocabulary);assert.equal(vocab.length,6);for(const original of fixtures.vocabulary){const s=vocab.find(s=>s.word===original.word);assert(s);assert.equal(s.prompt,original.definition);assert.equal(s.img,null);assert(words(s.note).includes(words(original.credit)),'Original card credit retained '+s.word);const start=steps.findIndex(p=>p.id===s.sourceStep),end=steps.indexOf(s);assert(start>=0&&start<end);assert(steps.slice(start+1,end).every(p=>p.vocabulary&&p.sourceStep===s.sourceStep),'Vocabulary follows source context '+s.word);}
 const after=steps.filter(s=>s.kind==='after');assert(after.length);for(const s of after){assert.equal(s.img,assetRoot+'book-17-page-29.jpg');assert.deepEqual(s.printedPages,[29],'Original lesson says show page 29');};for(const phrase of ['How has Dog had a colorful day?','How can you have a colorful day?'])assert(words(after.map(s=>s.prompt).join(' ')).includes(phrase));assert.equal(steps.at(-1).prompt,'Today we read Dog’s Colorful Day. We made predictions and also talked about why he had a colorful day.');assert.match(steps.at(-1).note,/Thursday/);
 for(const [file,digest]of Object.entries(fixtures.preservedFiles))assert.equal(hash(read(file)),digest,'All prior lesson/runtime bytes unchanged: '+file);
 assert.deepEqual([...read('week12-read-aloud.html').matchAll(/<script src="([^"]+)"/g)].map(m=>m[1]),['week12-read-aloud-plan-v1.js','week12-read-aloud-tuesday-plan-v2.js','week12-read-aloud-wednesday-plan-v1.js','week12-read-aloud-thursday-plan-v1.js','week12-read-aloud-v4.js']);const sw=read('sw.js');assert.match(sw,/const CACHE='eea-companion-v105'/);for(const file of ['week12-read-aloud.html','week12-read-aloud-v1.js','week12-read-aloud-v2.js','week12-read-aloud-v3.js','week12-read-aloud-v4.js','week12-read-aloud-plan-v1.js','week12-read-aloud-plan.json','week12-read-aloud-tuesday-plan-v1.js','week12-read-aloud-tuesday-plan-v2.js','week12-read-aloud-tuesday-plan.json','week12-read-aloud-wednesday-plan-v1.js','week12-read-aloud-wednesday-plan.json','week12-read-aloud-thursday-plan-v1.js','week12-read-aloud-thursday-plan.json','lesson-runner-week12.html'])assert(sw.includes("'./"+file+"'"),'Worker caches '+file);
 for(const sourceId of fixtures.resourceIds)assert([plan.source,...plan.resources.map(r=>r[1])].some(url=>url.includes(sourceId)),'Original resource accessible '+sourceId);
}

(async()=>{
 integrity();
 for(const embedded of [false,true]){
  const a=open(embedded),w=await ready(a),d=w.document;assert.deepEqual(copy(w.EEAReadAloudPlan),plan);assert.equal(d.querySelectorAll('iframe').length,0);
  const sourceNotes=[];for(const node of d.getElementById('sourceNotes').children){if(node.tagName==='H3')sourceNotes.push({title:node.textContent,paragraphs:[]});else if(node.tagName==='P')sourceNotes.at(-1).paragraphs.push(node.textContent);}assert.deepEqual(sourceNotes,plan.sourceNotes);
  assert.deepEqual([...d.querySelectorAll('#teacherNotes a')].map(a=>[a.textContent,a.getAttribute('href')]),[['Open original lesson plan',plan.source],...plan.resources]);for(const link of d.querySelectorAll('#teacherNotes a')){assert.equal(link.target,'_blank');assert(link.rel.includes('noopener')&&link.rel.includes('noreferrer'));}
  const baseline=a.w.history.length;
  for(let i=0;i<steps.length;i++){
   check(a,w,i);const url=a.w.location.href,len=a.w.history.length,st=copy(w.EEASectionState());for(let n=0;n<3;n++){d.querySelector('#teacherNotes summary').click();d.querySelector('#teacherNotes summary').click();}assert.equal(a.w.location.href,url);assert.equal(a.w.history.length,len);assert.deepEqual(copy(w.EEASectionState()),st);
   if(steps[i].discussionImages){const buttons=d.querySelectorAll('#discussionControls button');assert.equal(buttons.length,2);for(let n=0;n<2;n++){buttons[n].click();assert.equal(d.getElementById('bookImg').getAttribute('src'),steps[i].discussionImages[n].img);assert.equal(buttons[n].getAttribute('aria-pressed'),'true');assert.deepEqual(copy(w.EEASectionState()),st);assert.equal(a.w.location.href,url);assert.equal(a.w.history.length,len);}buttons[steps[i].sourceSlide===16?0:1].click();}
   for(let stop=1;stop<=steps[i].stops.length;stop++){d.getElementById('next').click();check(a,w,i,stop);}if(i<last)d.getElementById('next').click();
  }
  assert.equal(a.w.history.length,baseline+last+fixtures.stopCount,'Exactly one semantic history entry per screen and source reveal');assert.match(d.getElementById('next').textContent,/Finish Read Aloud/);a.w.localStorage.setItem('eea-lesson-auto-resume','enabled');for(let n=0;n<5;n++)d.getElementById('next').click();exit(a);close(a);
  for(const s of steps.slice(1)){const i=steps.indexOf(s),a=open(embedded,'week=12&day=Thursday&section=0&step='+i+'&stop='+s.stops.length),w=await ready(a);check(a,w,i,s.stops.length);w.document.getElementById('prev').click();check(a,w,s.vocabulary?steps.findIndex(p=>p.id===s.sourceStep):i-1);a.w.history.back();await until(()=>w.EEASectionState().step===i,'Back restores stop/vocab');check(a,w,i,s.stops.length);close(a);}
  for(const [raw,rawStop,index,stop]of [['bad','bad',0,0],['-1','-1',0,0],['1.5','.5',0,0],['Infinity','NaN',0,0],['999','999',last,0],[String(steps.findIndex(s=>s.stops.length)),'999',steps.findIndex(s=>s.stops.length),steps.find(s=>s.stops.length).stops.length]]){const a=open(embedded,'week=12&day=Thursday&section=0&step='+raw+'&stop='+rawStop+'&book=x&center=x&review=1'),w=await ready(a);check(a,w,index,stop);assert.equal(a.w.history.length,1);for(let n=0;n<4;n++){a.w.dispatchEvent(new a.w.Event('pageshow'));a.w.document.getElementById('frame')?.dispatchEvent(new a.w.Event('load'));}check(a,w,index,stop);close(a);}
  for(const [button,index]of [['prev',0],['backBtn',0],['backBtn',last],['next',last]]){const a=open(embedded,'week=12&day=Thursday&section=0&step='+index),w=await ready(a);a.w.localStorage.setItem('eea-lesson-auto-resume','enabled');for(let n=0;n<5;n++)w.document.getElementById(button).click();exit(a);close(a);}
  for(const [day,target]of [['Friday',4],['4',4],['',0],['bad',0],['-1',0],['5',0],['1.5',0],['Monday%20',0]]){const a=open(embedded,'week=12&section=0'+(day?'&day='+day:''));await until(()=>a.navigations.length,'Invalid day guarded');exit(a,target);assert.equal(a.w.EEAReadAloudPlan,undefined);close(a);}
  for(const named of ['Thursday','3']){const a=open(embedded,'week=12&day='+named+'&section=0'),w=await ready(a);check(a,w,0);close(a);}
  for(const [day,index,readNumber]of [['Monday',0,1],['0',0,1],['Tuesday',1,2],['1',1,2],['Wednesday',2,3],['2',2,3]]){const a=open(embedded,'week=12&day='+day+'&section=0'),w=await ready(a);assert.match(w.EEAReadAloudPlan.read,new RegExp('Read '+readNumber));assert.equal(w.EEASectionState().step,0);assert.equal(new URL(a.w.location.href).searchParams.get('day'),embedded?String(index):['Monday','Tuesday','Wednesday'][index]);assert.deepEqual(a.navigations,[]);close(a);}
  for(const day of ['Thursday','3']){const a=open(embedded,'week=12&day='+day+'&section=0'),w=await ready(a);assert.equal(w.EEAReadAloudPlan.title,'Dog’s Colorful Day');assert.match(w.EEAReadAloudPlan.read,/Read 1/);assert.equal(w.EEASectionState().step,0);assert.equal(new URL(a.w.location.href).searchParams.get('day'),embedded?'3':'Thursday');assert.deepEqual(a.navigations,[]);close(a);}
  for(const section of ['1','2','-1','bad','0.5','']){const a=open(embedded,'week=12&day=Thursday&section='+section);await until(()=>a.navigations.length,'Invalid section guarded');exit(a);close(a);}
 }
 console.log('PASS: Thursday independent full standard Read1/source access, 17 exact original scans, six text-only vocab cards and independently verified page mapping, prediction order, six vocabulary screens, every-screen DOM history/normalization and same-Thursday exits');
})().catch(e=>{console.error(e);process.exitCode=1;});
