// Source/DOM regressions. Independent originals are pinned in _fixtures.cjs;
// native joint history, image pixels and viewport geometry belong to _browser.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {JSDOM,ResourceLoader,VirtualConsole}=require('jsdom');
const {implForWrapper}=require('jsdom/lib/jsdom/living/generated/utils');const {serializeURL}=require('whatwg-url');
const fixtures=require('./test_week12_readaloud_fixtures.cjs');
const root=path.resolve(process.env.APP_ROOT||process.env.WEEK12_READALOUD_APP_ROOT||path.join(__dirname,'../v6-test'));
const read=f=>fs.readFileSync(path.join(root,f),'utf8'),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),copy=v=>JSON.parse(JSON.stringify(v)),words=s=>s.replace(/\s+/g,' ').trim();
const plan=JSON.parse(read('week12-read-aloud-plan.json')),steps=plan.steps,last=steps.length-1,origin='https://eea.test/v6-test/',assetRoot='assets/focus-3s/unit-2/week-4/festival-of-colors/';
const delay=ms=>new Promise(r=>setTimeout(r,ms));async function until(check,label){for(let i=0;i<300;i++){if(check())return;await delay(10);}assert.fail(label);}
class Files extends ResourceLoader{fetch(url){if(!url.startsWith(origin))return null;return Promise.resolve(fs.readFileSync(path.join(root,decodeURIComponent(new URL(url).pathname.slice('/v6-test/'.length)))));}}
function open(embedded=false,query='week=12&day=Monday&section=0'){
 const errors=[],navigations=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const file=embedded?'lesson-runner-week12.html':'week12-read-aloud.html';
 const w=new JSDOM(read(file),{url:origin+file+'?'+query,runScripts:'dangerously',resources:new Files(),virtualConsole:vc,beforeParse(w){implForWrapper(w.location)._locationObjectNavigate=url=>navigations.push(serializeURL(url));const Native=w.Date;w.Date=class extends Native{constructor(...a){super(...(a.length?a:['2026-10-05T12:00:00Z']));}static now(){return new Native('2026-10-05T12:00:00Z').getTime();}};}}).window;return{w,errors,navigations,embedded};
}
async function ready(a){await until(()=>a.w.document.readyState==='complete','Document ready');const w=a.embedded?a.w.document.getElementById('frame').contentWindow:a.w;await until(()=>w.document.readyState==='complete'&&typeof w.EEASectionState==='function','Reader initialized');return w;}
function close(a){assert.deepEqual(a.errors,[]);a.w.close();}
function expected(step,stop=0){return{step,index:step,total:steps.length,atStart:step===0,atEnd:step===last&&stop===steps[step].stops.length,stopPending:stop<steps[step].stops.length,vocabulary:!!steps[step].vocabulary,stop};}
function check(a,w,step,stop=0){assert.deepEqual(copy(w.EEASectionState()),expected(step,stop));const s=steps[step],d=w.document;assert.equal(d.getElementById('bookImg').getAttribute('src'),s.img);assert.equal(d.getElementById('teachingStop').hidden,stop===0);assert.equal(d.getElementById('stopText').textContent,stop?s.stops[stop-1]:'');assert.equal(d.getElementById('prompt').textContent,s.prompt);assert.equal(d.querySelector('.stage').classList.contains('spread'),!!s.bookPage);assert.equal(d.getElementById('teacherNotes').open,false);assert(d.getElementById('teacherText').textContent.includes(s.note));for(const [win,day]of [[a.w,a.embedded?'0':'Monday'],[w,'Monday']]){const p=new URL(win.location.href).searchParams;assert.equal(p.get('week'),'12');assert.equal(p.get('day'),day);assert.equal(p.get('section'),'0');assert.equal(p.get('step'),String(step));assert.equal(p.get('stop'),String(stop));for(const field of ['book','center','review'])assert(!p.has(field));}assert.deepEqual(a.navigations,[],'No unexpected redirect');}
function exit(a,day=0){assert.equal(a.navigations.length,1,'Exactly one top-level navigation');const u=new URL(a.navigations[0]);assert.equal(u.pathname,'/v6-test/daily-lessons.html');assert.equal(u.searchParams.get('week'),'12');assert.equal(u.searchParams.get('day'),String(day));assert.equal(a.w.localStorage.getItem('eea-lesson-auto-resume'),null);}
function imageSize(bytes){if(bytes.readUInt32BE(0)===0x89504e47)return[bytes.readUInt32BE(16),bytes.readUInt32BE(20)];assert.equal(bytes.readUInt16BE(0),0xffd8);let i=2;while(i<bytes.length){assert.equal(bytes[i++],0xff);while(bytes[i]===0xff)i++;const m=bytes[i++],len=bytes.readUInt16BE(i);if([0xc0,0xc1,0xc2].includes(m))return[bytes.readUInt16BE(i+5),bytes.readUInt16BE(i+3)];i+=len;}assert.fail('Image header');}
function integrity(){
 assert.equal(plan.title,'Festival of Colors');assert.equal(plan.authors,'Kabir Sehgal and Surishtha Sehgal');assert.equal(plan.illustrator,'Vashti Harrison');assert.match(plan.read,/Read 1/);assert.equal(steps.length,28);assert.equal(new Set(steps.map(s=>s.id)).size,28);
 const manifest=JSON.parse(read(assetRoot+'source-manifest.json'));assert.equal(manifest.source,fixtures.sourceGuide);assert.deepEqual(manifest.readingOrder,fixtures.order);assert.equal(manifest.images.length,21);
 for(const original of fixtures.images){const file=original.file||'guide-'+String(original.sourceSlide).padStart(2,'0')+'.jpg',bytes=fs.readFileSync(path.join(root,assetRoot,file)),actual=manifest.images.find(x=>x.file===file);assert(actual);assert.equal(hash(bytes),original.sha256,'Original bytes '+file);assert.deepEqual(imageSize(bytes),[original.width,original.height]);for(const key of ['sha256','width','height'])assert.equal(actual[key],original[key]);}
 const book=steps.filter(s=>s.kind==='book');assert.deepEqual(book.map(s=>s.sourceSlide),fixtures.order);assert.deepEqual(book.flatMap(s=>s.printedPages),Array.from({length:30},(_,i)=>i+1),'Cover/title then all printed pages 1–30 exactly once');
 for(const s of book){assert.equal(s.bookPage,true);assert.equal(s.img,assetRoot+'guide-'+String(s.sourceSlide).padStart(2,'0')+'.jpg');if(s.sourceSlide>=3)assert(words(s.note).includes(words(fixtures.guideNotes[s.sourceSlide])),'Every guide commentary word retained: '+s.sourceSlide);}
 const stopSteps=steps.filter(s=>s.stops.length);assert.deepEqual(stopSteps.map(s=>s.sourceSlide),[3,4,8,10,13,16]);assert.equal(stopSteps.flatMap(s=>s.stops).length,6);const meanings=[/flowers are blooming.*festival is a celebration/i,/Holy heh/,/Hibiscus, orchid, marigold, and iris/,/separating.*sorting.*leaves and stems/i,/neighbors.*people who live near/i,/forgive.*stop being upset or angry/i];stopSteps.forEach((s,i)=>assert.match(s.stops[0],meanings[i]));
 const vocab=steps.filter(s=>s.vocabulary);assert.deepEqual(vocab.map(s=>s.word),['bloom','festival','separate','neighbor','forgive']);assert.deepEqual(vocab.map(s=>s.prompt),['when a flower opens','a celebration','to sort','someone who lives near you','to stop being upset or angry at someone']);assert.deepEqual(vocab.map(s=>s.sourceSlide),[3,3,10,13,16]);for(const s of vocab){const start=steps.findIndex(p=>p.id===s.sourceStep),end=steps.indexOf(s);assert(start>=0&&start<end);assert(steps.slice(start+1,end).every(p=>p.vocabulary&&p.sourceStep===s.sourceStep),'Vocabulary follows its original spread');}
 assert.equal(words(plan.sourceNotes[0].paragraphs.join(' ')),words(fixtures.lessonRead1),'Every original common guidance/Read1 word retained');assert.match(plan.teacherNotes,/Note From the Authors.*physical book/);assert.match(plan.teacherNotes,/pp\.17–18.*printed-page order/);assert.match(plan.teacherNotes,/pp\.28–29.*27–28 and 29–30/);assert.match(steps.at(-1).note,/Finish returns to Monday/);
 const after=steps.filter(s=>s.kind==='after');assert.equal(after.length,2);for(const s of after)assert.deepEqual(s.discussionImages.map(p=>path.basename(p.img)),['guide-16.jpg','guide-17.jpg']);
 assert.deepEqual([...read('week12-read-aloud.html').matchAll(/<script src="([^"]+)"/g)].map(m=>m[1]),['week12-read-aloud-plan-v1.js','week12-read-aloud-v1.js']);assert.match(read('daily-lessons.html'),/MAX_WEEK=12,AUTO_MAX_WEEK=9/);const sw=read('sw.js');assert.match(sw,/const CACHE='eea-companion-v101'/);for(const file of ['week12-read-aloud.html','week12-read-aloud-v1.js','week12-read-aloud-plan-v1.js','week12-read-aloud-plan.json','lesson-runner-week12.html'])assert(sw.includes("'./"+file+"'"),'Worker caches '+file);assert.equal(hash(read('week11-read-aloud-v4.js')),fixtures.oldReaderSha256);
}
(async()=>{
 integrity();
 for(const embedded of [false,true]){
  const a=open(embedded),w=await ready(a),d=w.document;assert.deepEqual(copy(w.EEAReadAloudPlan),plan);assert.equal(d.querySelectorAll('iframe').length,0);
  const sourceNotes=[];for(const node of d.getElementById('sourceNotes').children){if(node.tagName==='H3')sourceNotes.push({title:node.textContent,paragraphs:[]});else if(node.tagName==='P')sourceNotes.at(-1).paragraphs.push(node.textContent);}assert.deepEqual(sourceNotes,plan.sourceNotes);
  assert.deepEqual([...d.querySelectorAll('#teacherNotes a')].map(a=>[a.textContent,a.getAttribute('href')]),[['Open original lesson plan',plan.source],...plan.resources]);for(const link of d.querySelectorAll('#teacherNotes a')){assert.equal(link.target,'_blank');assert(link.rel.includes('noopener')&&link.rel.includes('noreferrer'));}
  const baseline=a.w.history.length;
  for(let i=0;i<steps.length;i++){
   check(a,w,i);const url=a.w.location.href,len=a.w.history.length,st=copy(w.EEASectionState());for(let n=0;n<3;n++){d.querySelector('#teacherNotes summary').click();d.querySelector('#teacherNotes summary').click();}assert.equal(a.w.location.href,url);assert.equal(a.w.history.length,len);assert.deepEqual(copy(w.EEASectionState()),st);
   if(steps[i].discussionImages){const buttons=d.querySelectorAll('#discussionControls button');assert.equal(buttons.length,2);for(let n=0;n<2;n++){buttons[n].click();assert.equal(d.getElementById('bookImg').getAttribute('src'),steps[i].discussionImages[n].img);assert.equal(buttons[n].getAttribute('aria-pressed'),'true');assert.deepEqual(copy(w.EEASectionState()),st);assert.equal(a.w.location.href,url);assert.equal(a.w.history.length,len);}buttons[steps[i].sourceSlide===16?0:1].click();}
   for(let stop=1;stop<=steps[i].stops.length;stop++){d.getElementById('next').click();check(a,w,i,stop);}if(i<last)d.getElementById('next').click();
  }
  assert.equal(a.w.history.length,baseline+last+6,'One semantic entry for each screen advance and source stop');assert.match(d.getElementById('next').textContent,/Finish Read Aloud/);a.w.localStorage.setItem('eea-lesson-auto-resume','enabled');for(let n=0;n<5;n++)d.getElementById('next').click();exit(a);close(a);
  for(const s of steps.filter(s=>s.stops.length||s.vocabulary)){const i=steps.indexOf(s),a=open(embedded,'week=12&day=Monday&section=0&step='+i+'&stop='+s.stops.length),w=await ready(a);check(a,w,i,s.stops.length);w.document.getElementById('prev').click();check(a,w,s.vocabulary?steps.findIndex(p=>p.id===s.sourceStep):i-1);a.w.history.back();await until(()=>w.EEASectionState().step===i,'Back restores stop/vocab');check(a,w,i,s.stops.length);close(a);}
  for(const [raw,rawStop,index,stop]of [['bad','bad',0,0],['-1','-1',0,0],['1.5','.5',0,0],['Infinity','NaN',0,0],['999','999',last,0],['5','999',5,1]]){const a=open(embedded,'week=12&day=Monday&section=0&step='+raw+'&stop='+rawStop+'&book=x&center=x&review=1'),w=await ready(a);check(a,w,index,stop);assert.equal(a.w.history.length,1);for(let n=0;n<4;n++){a.w.dispatchEvent(new a.w.Event('pageshow'));a.w.document.getElementById('frame')?.dispatchEvent(new a.w.Event('load'));}check(a,w,index,stop);close(a);}
  for(const [button,index]of [['prev',0],['backBtn',0],['backBtn',last],['next',last]]){const a=open(embedded,'week=12&day=Monday&section=0&step='+index),w=await ready(a);a.w.localStorage.setItem('eea-lesson-auto-resume','enabled');for(let n=0;n<5;n++)w.document.getElementById(button).click();exit(a);close(a);}
  for(const [day,target]of [['Tuesday',1],['Wednesday',2],['Thursday',3],['Friday',4],['1',1],['2',2],['3',3],['4',4],['',0],['bad',0],['-1',0],['5',0],['1.5',0],['Monday%20',0]]){const a=open(embedded,'week=12&section=0'+(day?'&day='+day:''));await until(()=>a.navigations.length,'Invalid day guarded');exit(a,target);assert.equal(a.w.EEAReadAloudPlan,undefined);close(a);}
  for(const section of ['1','2','-1','bad','0.5','']){const a=open(embedded,'week=12&day=Monday&section='+section);await until(()=>a.navigations.length,'Invalid section guarded');exit(a);close(a);}
 }
 console.log('PASS: 21 original assets, complete original Read1/guide notes, 28 screens, six gated stops, five vocabulary screens, both discussion spreads, DOM history/normalization, repeated exits and unavailable-day guards');
})().catch(e=>{console.error(e);process.exitCode=1;});
